name: Snapcraft Build and Publish
env:
  SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_TOKEN }}

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
    - uses: snapcore/action-build@v1
      id: build
    - uses: actions/upload-artifact@v3
      with:
        name: snap
        path: ${{ steps.build.outputs.snap }}
    - uses: snapcore/action-publish@v1
      with:
        snap: ${{ steps.build.outputs.snap }}
        release: stable
